//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEncyclopedia.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.EuroTrophy_Club = new HashSet<EuroTrophy_Club>();
            this.Trophy_Club = new HashSet<Trophy_Club>();
        }
    
        public int Club_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Site { get; set; }
        public int ID_League { get; set; }
        public Nullable<int> ID_EuroLeague { get; set; }
        public int ID_City { get; set; }
        public Nullable<int> ID_Manager { get; set; }
        public int ID_Stadium { get; set; }
    
        public virtual City City { get; set; }
        public virtual EuroLeague EuroLeague { get; set; }
        public virtual League League { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Stadium Stadium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EuroTrophy_Club> EuroTrophy_Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trophy_Club> Trophy_Club { get; set; }
    }
}
