//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEncyclopedia.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EuroTrophy_Club
    {
        public int EuroTrophy_Club_ID { get; set; }
        public int ID_Euro_Trophy { get; set; }
        public int ID_Club { get; set; }
        public string Count { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual EuroTrophy EuroTrophy { get; set; }
    }
}
