//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEncyclopedia.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EuroTrophy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EuroTrophy()
        {
            this.EuroTrophy_Club = new HashSet<EuroTrophy_Club>();
        }
    
        public int EuroTrophy_ID { get; set; }
        public string Name { get; set; }
        public int ID_EuroLeague { get; set; }
        public string Photo { get; set; }
    
        public virtual EuroLeague EuroLeague { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EuroTrophy_Club> EuroTrophy_Club { get; set; }
    }
}
